// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxVw0hrn57M2hl_XvNiiMlIGENWCzt5Ew',
    appId: '1:399211502290:web:a56e24b74fbb5d7c512b0b',
    messagingSenderId: '399211502290',
    projectId: 'batchfirebaseproject',
    authDomain: 'batchfirebaseproject.firebaseapp.com',
    storageBucket: 'batchfirebaseproject.firebasestorage.app',
    measurementId: 'G-P4R9TK28H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXvYeTGgk9pSnwdfTH-yCgxpoFdvdT9Qs',
    appId: '1:399211502290:android:43677b2ee0a21a1e512b0b',
    messagingSenderId: '399211502290',
    projectId: 'batchfirebaseproject',
    storageBucket: 'batchfirebaseproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0jAI5eqZbCiNCfI0hMSjFFaHAFvX95A',
    appId: '1:399211502290:ios:d5795ee9f9749bdf512b0b',
    messagingSenderId: '399211502290',
    projectId: 'batchfirebaseproject',
    storageBucket: 'batchfirebaseproject.firebasestorage.app',
    iosBundleId: 'com.foodgo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW0jAI5eqZbCiNCfI0hMSjFFaHAFvX95A',
    appId: '1:399211502290:ios:d5795ee9f9749bdf512b0b',
    messagingSenderId: '399211502290',
    projectId: 'batchfirebaseproject',
    storageBucket: 'batchfirebaseproject.firebasestorage.app',
    iosBundleId: 'com.foodgo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxVw0hrn57M2hl_XvNiiMlIGENWCzt5Ew',
    appId: '1:399211502290:web:f3255feec4f91f27512b0b',
    messagingSenderId: '399211502290',
    projectId: 'batchfirebaseproject',
    authDomain: 'batchfirebaseproject.firebaseapp.com',
    storageBucket: 'batchfirebaseproject.firebasestorage.app',
    measurementId: 'G-4Y84T0PKLB',
  );
}
